# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  check-types:
    desc: Check types
    cmds:
      - ./node_modules/.bin/tsc --noEmit
    silent: false

  lint:
    desc: Run linter
    cmds:
      - ./node_modules/.bin/oxlint .
    silent: false

  lint-fix:
    desc: Run linter with auto-fix
    cmds:
      - ./node_modules/.bin/oxlint . --fix
    silent: false

  check-formatting:
    desc: Check formatting
    cmds:
      - ./node_modules/.bin/oxfmt . --check
    silent: false

  check-all:
    desc: Run all checks
    cmds:
      - task: check-types
      - task: lint
      - task: check-formatting
    silent: false

  compile:
    desc: Compile the extension
    env:
      NODE_ENV: production
    cmds:
      - ./node_modules/.bin/tsup
    silent: false

  format:
    desc: Format code
    cmds:
      - ./node_modules/.bin/oxfmt . --write
    silent: false

  unit-tests:
    desc: Run unit tests
    cmds:
      - ./node_modules/.bin/vitest run src {{.CLI_ARGS}}
    silent: false

  unit-test-coverage:
    desc: Run unit tests with coverage
    cmds:
      - ./node_modules/.bin/vitest run src --coverage {{.CLI_ARGS}}
    silent: false

  extension-tests:
    desc: Run extension tests
    cmds:
      - node test/extension/index.js {{.CLI_ARGS}}
    silent: false

  pull-models:
    desc: Pull required models for integration tests
    cmds:
      - ollama pull smollm:135m
      - ollama pull qwen3:0.6b
      - ollama pull kimi-k2.5:cloud
    silent: false

  integration-tests:
    desc: Run integration tests
    deps: [pull-models]
    cmds:
      - ./node_modules/.bin/vitest run -c vitest.integration.config.js test/integration {{.CLI_ARGS}}
    silent: false

  precommit:
    desc: Run pre-commit checks
    deps: [check-types]
    cmds:
      - task: lint-fix
      - task: format
    silent: false

  prerelease:
    desc: Create a pre-release
    deps: [compile]
    cmds:
      - ./node_modules/.bin/zx ./scripts/release.mjs --pre-release {{.CLI_ARGS}}
    silent: false

  release:
    desc: Release the extension
    deps: [compile]
    cmds:
      - ./node_modules/.bin/zx ./scripts/release.mjs {{.CLI_ARGS}}
    silent: false

  test-all:
    desc: Run all tests
    cmds:
      - task: unit-tests
      - task: extension-tests
      - task: integration-tests
    silent: false

  test-build-release:
    desc: Test, Build & Release
    deps: [check-all, test-alle]
    cmds:
      - task: release
    silent: false

  watch:
    desc: Watch for changes and recompile
    cmds:
      - ./node_modules/.bin/tsup --watch
    silent: false
